### ISSUE TITLE
Randomly teleported into void after entering Nether

### ISSUE THREAD

**Issue by agaertner** [qouteall/ImmersivePortalsMod#88] opened 2020-02-23 21:13 UTC
All players suddenly get randomly teleported into empty space and the server console gets spammed with Portal requests.

Recreate:
Enter Nether
Wait 10 seconds.
Player get teleported into empty space or walls (and dies) and server console spams:
``[Portal] request teleport <player> in minecraft:the_nether to <x> <y> <z>``

this started to happen after restarting the server several times and having relit / rebuild the nether portal in almost the same area. It worked fine before (or we didn't notice) and there are no mod incompatibilities.

**Comment by qouteall** [comment] 2020-02-24 00:44
1.14 or 1.15? Did the log say that player cannot teleport through xxx? Show the full log.

**Comment by qouteall** [comment] 2020-02-24 00:57
Are you using the latest version of this.mod?

**Comment by agaertner** [comment] 2020-02-24 02:40
yes I use the latest fabric version. 

[2020-02-23-1.log](https://github.com/qouteall/ImmersivePortalsMod/files/4242948/2020-02-23-1.log) here's one log. Scroll down and you will quickly see the spam. That's where players are getting teleported into walls or empty spaces after a delay of 5 secs after entering Nether.

edit: also when relighting a portal in the overworld it creates another portal around the same area (like 10 blocks away) of the old frame in the Nether instead of using the existing one. Ie. it spams frames and fails to detect old one.

**Comment by qouteall** [comment] 2020-02-24 02:49
The fabric api seems old, try to install latest fabric api.
If it still does not work, remove all other mods and try again.

**Comment by agaertner** [comment] 2020-02-24 15:23
It's the newest fabric api and I won't reinstall, because it worked for several hours and I did test it one mod at a time. 

these are all the mods https://i.imgur.com/HsKcSDW.png

they didn't conflict in anyway.

**Comment by qouteall** [comment] 2020-02-24 15:31
It's weird. Please show the client log.

**Comment by qouteall** [comment] 2020-02-24 15:36
What do you mean "test it one mod at a time"? Does this issue manifest when only this mod and fabric api installed? There may be potential conflict. (backup the world before uninstalling mods)

**Comment by qouteall** [comment] 2020-02-24 15:56
Well as it's random you don't need to test it more. I am going to rewrite the position sync system. The current system is complex and error prone.

**Comment by agaertner** [comment] 2020-02-24 16:52
> What do you mean "test it one mod at a time"?

Delete world.
Install mod.
Reboot server and join.
Everything ok?
Install next mod.
Delete world.
reboot server and join.
repeat.

As I said. The error came up after several restarts and me rebuilding the portal in the same chunk several times.

**Comment by qouteall** [comment] 2020-02-25 08:29
Maybe the player stuck in wall somehow and server keep sending teleport request but client did not accept the packet. The client log should be spammed by "denied position packet".
Does this issue happen if you go somewhere far and build another portal?

**Comment by qouteall** [comment] 2020-02-25 08:36
I updated 0.13 and changed some position sync details. Check whether this issue still exists.
(I didn't rewrite the positon sync system because rewriting may cause more problems)

**Comment by agaertner** [comment] 2020-02-25 17:33
Here's the client log corresponding to aboves server log.
[2020-02-23-3.log](https://github.com/qouteall/ImmersivePortalsMod/files/4251255/2020-02-23-3.log)

**Comment by qouteall** [comment] 2020-02-26 04:30
It says "Sending packet net.minecraft.class_2817@3c3e46fa to server failed, not connected!"
But you can log in the server, weird.
Maybe it's caused by other mods. Try to remove half of mods and try again until you find which mod it's incompatible with.

**Comment by agaertner** [comment] 2020-02-26 18:41
Maybe it has combatibility issues with https://github.com/zlainsama/PeacefulSurface
because I installed it a  bit later and before we had the issue with the portal.
https://i.imgur.com/xS8G7PU.png our current mod list.

**Comment by qouteall** [comment] 2020-09-25 11:45
Should be fixed in the new versions

**Closed as completed** 2020-09-25 11:44 UTC
