### ISSUE TITLE
Bug in 1.15.2 with Optifine shader

### ISSUE THREAD

**Issue by Ironwally** [qouteall/ImmersivePortalsMod#131] opened 2020-03-30 16:47 UTC
When I use a shader with this mod, then while I am looking at a portal / through a portal, all the text glitches out and gets a kind of blueish color + kind of getting doubled.
Secondly while I look at a portal, I have really extrem framerate drops. I´m leaving a screenshot of what it looks like.
I already checked that it has nothing to do with a resource pack or anything else. Im pretty sure it must have something to do with Immersive Portals, or 1.15.2 Optifine version, as it still is only a preview.
![Minecraft 1 15 2 Shader or Portal mod Bug Report 2](https://user-images.githubusercontent.com/62899274/77938804-8b9a9700-72b6-11ea-8d2e-f5447558bd0a.png)

**Comment by qouteall** [comment] 2020-03-31 03:29
Which shader are you using?

**Comment by Ironwally** [comment] 2020-03-31 07:31
It happens to me with every shader I use: I've used SEUS any version and  Sildurs Vibrant Shaders v1.27 High or Medium

**Comment by qouteall** [comment] 2020-04-03 04:52
I cannot reproduce it with the latest optifine without resouce pack

**Comment by Giggitybyte** [comment] 2020-04-07 20:44
I am able to reproduce something similar to this. These rendering errors only happen when a portal is rendered; if it's off screen everything looks normal.

Sildurs Vibrant v1.27 Extreme:
https://s.thegiggitybyte.me/bm9AB.png
https://s.thegiggitybyte.me/lhpLE.png
https://s.thegiggitybyte.me/OAmQU.png
https://s.thegiggitybyte.me/Gbe15.jpg
https://s.thegiggitybyte.me/bRUOp.png

Sildurs Enhanced Default v1.10:
https://s.thegiggitybyte.me/DHUMb.png
https://s.thegiggitybyte.me/3or70.png
https://s.thegiggitybyte.me/PpuNb.png
https://s.thegiggitybyte.me/JuIWW.png

Immersive Portals 0.23
OptiFine_1.15.2_HD_U_G1_pre13
optifabric-1.0.0-beta8

I'm running this with a handful of other mods, however I believe the most relevant ones that could also be conflicting are Phosphor (0.5.2+build.6) and Lithium (0.4.6)

**Comment by qouteall** [comment] 2020-04-08 02:26
I can reproduce this issue now. And set fog to off can avoid this issue.

**Comment by qouteall** [comment] 2020-04-08 02:27
ok fixed. it will be in the next version

**Comment by bertin0** [comment] 2020-04-08 12:38
I have built and tested the latest commits and it seema to partially fix the issue. On Sildur's Vibrant everything is ok, but on Enhanced Default (and also on the internal shaders), the purple wireframe still remains. Hopefully you'll have time to look into it.

**Comment by Ironwally** [comment] 2020-04-09 21:57
Ah great! Thanks, cool work. Sorry that I didn't answer, somehow, didn't see the email

**Closed as completed** 2020-04-14 04:01 UTC
