### ISSUE TITLE
Immersive Portals makes the Rat Pouch from Rat's Mischief break

### ISSUE THREAD

**Issue by CammiePone** [qouteall/ImmersivePortalsMod#595] opened 2021-02-21 23:57 UTC
It causes rats to lose their owners, their skin, and their names, as well as deleting them if you Shift + Right Click on the rat with the back, which would normally pick up the rat just fine.

I'm not sure if this is something that needs to be fixed on your end or Rat's end, so I've reported it to both.

**Comment by qouteall** [comment] 2021-02-22 09:31
post the log

**Comment by CammiePone** [comment] 2021-02-22 17:24
Reason I didn't was because there's nothing in the log, but here it is:
https://pastebin.com/1WqjJABb

(this is with a brand new world and instance, with nothing but Immersive Portals and Rat's Mischief. I put a rat in the pouch and took it out 4 times.)

**Comment by IdrisQe** [comment] 2021-03-14 20:51
Adding to this.

It doesn't just break the pouch. Whenever you unload chunks containing a rat and come back, their data will have been removed and replaced. There is no log detailing why this happens; I searched. 

It's definitely an issue between these two mods.

https://github.com/Ladysnake/Rats-Mischief/issues/14

**Comment by qouteall** [comment] 2021-03-15 07:57
@IdrisQe How did you "unload"? Did you go through custom portal api's portal? Or vanilla nether portal? Or going away and come back?

**Comment by IdrisQe** [comment] 2021-03-15 09:44
All I did was unload the area by (at first) saving and quitting, (and then to confirm the issue) travelling far away - both ways of unloading the chunks seem to trigger the issue. There was no changing of dimensions (in fact I don't even have a Nether Portal set up yet)

Honestly I'm still not entirely convinced it's solely an issue between these two mods given it's a pretty strange thing to happen... Mainly added the info here since it only seemed to start once I added Immersive Portals to my pack, and I was directed toward it being an incompatability with Immersive Portals that was previously documented.

It's too late at night (well technically too early in the morning) to do so now, but I'll probably set up a testing instance with just the two (and dependencies) to make sure it's not something involving more mods once I wake up.

**Comment by IdrisQe** [comment] 2021-03-15 21:43
I made a test instance with minimal setup and no config changes for either mod.
**Confirmed the issue with only:**
_Fabric Loader 0.11.3, Fabric API 0.320, GeckoLib 3.0.23, Rats Mischief 1.0.4, Immersive Portals 0.80_

**Steps to reproduce:**
-Add all mods _except Immersive Portals_
-Start game
-Create world
-[_Possibly Important?_] Go away from spawn chunks, as they are, to my knowledge, kept loaded all the time
-Tame a rat, make it sit
-Exit world
-Load world. _Rat is still the same, and still able to be commanded_
-Exit game
-_Add Immersive Portals_
-Start game
-Load world. _Rat color is randomized, and rat can no longer be commanded._
-Exit world
-Load world. _Rat color is randomized again, and remains ownerless._

Checked with each world load; no log anomalies to report.

**Comment by qouteall** [comment] 2021-03-17 03:49
probably fixed in 0.84 https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.84-1.16

**Closed as completed** 2021-03-17 03:50 UTC

**Comment by IdrisQe** [comment] 2021-03-17 06:09
I'll check once I download it!

**Comment by IdrisQe** [comment] 2021-03-17 19:36
Having done some minimal testing, it seems to have fixed the issue!
Interestingly, it seems to have _retroactively_ fixed the issue too-
My rat, which with the issue, was not appearing tamed, now seems to function as tamed again despite having not touched it, and has reverted to its original (I think?) colour.
