### ISSUE TITLE
[Bug] Copy item

### ISSUE THREAD

**Issue by herobrinein** [qouteall/ImmersivePortalsMod#1579] opened 2024-07-13 16:15 UTC
### Is it a mod compatibility issue?

Select One

### Minecraft version

1.20.4

### Describe the issue

When playing multiplayer games, player A opens the Shulker Box, player B destroys it, and player A still stays on the screen of opening the Shulker Box. At this time, they can take out items for copying

**Comment by qouteall** [comment] 2024-07-14 05:53
I tested it and cannot reproduce the issue. I need to know whether it's a mod compatibility issue. Can you reproduce the issue with only iPortal and Fabric API (both server side and client side)?

**Comment by herobrinein** [comment] 2024-10-25 11:58
> I tested it and cannot reproduce the issue. I need to know whether it's a mod compatibility issue. Can you reproduce the issue with only iPortal and Fabric API (both server side and client side)?

I'm sorry, I haven't been online for a long time and only now I saw this message, I'll reply within a few days

**Comment by herobrinein** [comment] 2024-10-26 10:26
Minecraft 1.20.4 
Fabric 0.15.9
FabricAPI 0.97.0
immersive-portals-5.1.8-mc1.20.4-fabric
Mods:
![image](https://github.com/user-attachments/assets/1c72e57f-76e2-4b7b-a7a4-381048c16c2b)
Video:

https://github.com/user-attachments/assets/56e4c162-ec50-46be-9f7b-66754a4b809e

@qouteall

**Comment by qouteall** [comment] 2024-11-03 02:15
Should be fixed in this version https://github.com/iPortalTeam/ImmersivePortalsMod/releases/tag/v5.1.10-mc1.20.4

**Closed as completed by qouteall** 2024-11-03 02:15 UTC
Labels: IMPORTANT
