### ISSUE TITLE
Incompatible with Cauldron Dyeing

### ISSUE THREAD

**Issue by LokeYourC3PH** [qouteall/ImmersivePortalsMod#1404] opened 2023-08-05 15:59 UTC
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

I chose "Is it a mod compatibility issue?" as "Yes" because I think it's very likely to be the case. Anyhow, upon now having updated a few mods, amongst which is Sodium & Indium, even though Immersive Portals updated to be compatible, it crashes when creating a new world with the following crash:

[crash-2023-08-06_00.55.56-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12267634/crash-2023-08-06_00.55.56-client.txt)

That's it :)

**Comment by qouteall** [comment] 2023-08-06 05:14
There are many mods. To find which mod is incompatible, you can do a binary search.

The binary search is a way of finding the incompatible mod without removing the mods one-by-one.

The procedure is simple:
1. Backup the world because removing mod cause its content to be removed.
2. Remove half of the existing mods, and put them aside.
3. Run the game.
4. Does the issue still exist?
If YES: Repeat from step 2 with the current mods.
If NO: Swap out the current mods with the ones set aside, and repeat from step 1.
5. Repeat this process until the problematic mod/s have been found.

**Comment by LokeYourC3PH** [comment] 2023-08-06 06:06
Yeah, I'm aware on how to do batch checking, I did that since like 1.2.5 days of Minecraft modding in the earliest stages of it. The issue is that, I hoped there would be a clear indicator for you (since Immersive Portals is the mod that is mentioned) as to what causes it, without me needing to remove 20+ mods in batches each time from like 300+ mods in total. I am doing that now though, then.

**Comment by LokeYourC3PH** [comment] 2023-08-06 06:58
EDIT: It's 100% your mod. After having tried removing over 300+ mods, I was left with only these:

![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/5807595/0f84f410-8bb4-42e0-a173-4eaa8d842125)

And even then, it crashed. These are the most basic, core mods needed basically. However, after removing Immersive Portals, it worked immediately, crashes stopped occurring. It is 100% on Immersive Portals causing this, it is somehow incompatible with Sodium on a basic level since the update. And to confirm this, I had even removed Indium and Iris to really, REALLY leave out any other suspects, leaving behind Immersive Portals, Sodium and Fabric API, nothing else. Proof:

![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/5807595/3d96c49c-7007-4f7d-b3c3-d445563210b7)

The log that followed, was this:
[crash-2023-08-06_15.54.19-client.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12268831/crash-2023-08-06_15.54.19-client.txt)

**Comment by Cramber25** [comment] 2023-08-06 14:38
I have the same issue with only Sodium 0.5 and the newest Immersive Portals. My game also crashes when joining a server with these mods installed.

![image](https://github.com/iPortalTeam/ImmersivePortalsMod/assets/46049779/acb7270b-9a33-4c86-b71a-02e11a7b5b08)

**Comment by NyxWinter** [comment] 2023-08-06 16:06
I have the exact same issue, except when using iris **and** having loaded shaders (tested with SUES PTGI  HRR Test 2.1 GFME v1.11.1), then it works just fine.

**Comment by LokeYourC3PH** [comment] 2023-08-06 16:56
> I have the exact same issue, except when using iris **and** having loaded shaders (tested with SUES PTGI HRR Test 2.1 GFME v1.11.1), then it works just fine.

Lol? Works fine _**WITH SHADERS**_ but not without, wtf 😂

**Comment by drakosoldier298** [comment] 2023-08-07 01:33
iris says it must be fixed by immersive portals https://github.com/IrisShaders/Iris/issues/2078#issuecomment-1667038442

**Comment by qouteall** [comment] 2023-08-07 10:45
I only tested this issue with shaders on so didn't found this issue. It's also a mixin remapping issue that does not occur in dev env. It's going to be fixed.

**Comment by qouteall** [comment] 2023-08-07 10:55
~Probably fixed in 3.2.3~

**Comment by qouteall** [comment] 2023-08-08 10:43
@LokeYourC3PH I cannot reproduce the issue with Sodium, Iris and Indium.

Post the log to help diagnose the issue.

**Comment by LokeYourC3PH** [comment] 2023-08-08 12:04
I have traced the issue down to the following mod: https://modrinth.com/mod/cauldron-dyeing

Out of all mods, it's really the last mod I expected to cause this issue, but yeah, after trying to remove in batches for about an hour, I tracked it down to the Cauldron Dyeing mod.

HOWEVER, there are more mods that have this issue, not just Cauldron Dyeing. Meaning, that Immersive Portals is the core issue to this. I will look into what other mods are causing this except for that one, but it will take a while.

**Comment by qouteall** [comment] 2023-08-08 12:22
I tested it and the llog shows 
```
java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer failed
...
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for cauldron-dyeing.mixins.json:sodium.SodiumBlockRendererMixin from mod cauldron_dyeing during activity: [Transform -> Method cauldron_dyeing$redirectGetColors(Lme/jellysquid/mods/sodium/client/model/quad/blender/ColorBlender;Lnet/minecraft/class_1920;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/model/quad/ModelQuadView;Lme/jellysquid/mods/sodium/client/model/quad/blender/ColorSampler;Ljava/lang/Object;)[I -> INVOKESPECIAL -> me/jellysquid/mods/sodium/client/model/quad/blender/FlatColorBlender::<init>:()V]
...
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.model.quad.blender.FlatColorBlender
...
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.model.quad.blender.FlatColorBlender
```

This seem to be an issue of Cauldron Dying mixining into Sodium but Sodium updated so it fails. Seems not related with ImmPtl.

In this case the log provides useful information but crash report doesn't. ~I am going to change issue template to mandate providing logs.~

**Comment by LokeYourC3PH** [comment] 2023-08-08 12:22
Ok I see, then in that case some other mods causing the same issues all fall under that category that they need to update for latest Sodium.

**Comment by qouteall** [comment] 2023-08-08 12:24
As I tested, cauldron dyeing crashes with sodium without ImmPtl. This issue is unrelated with ImmPtl.

**Closed as completed by qouteall** 2023-08-08 12:24 UTC
Labels: Not ImmPtl's Fault
