### ISSUE TITLE
Crash with rlsl

### ISSUE THREAD

**Issue by pocinhas** [qouteall/ImmersivePortalsMod#1256] opened 2023-01-22 14:11 UTC
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

i've reported the issue to another dev and they directed me to here, [original issue](https://github.com/RelativityMC/raise-sound-limit-simplified/issues/1). Something related to sounds they said

### Post the log here

```shell
on the linked issue ^^
```

**Comment by qouteall** [comment] 2023-02-04 07:24
Probably fixed in ImmPtl 2.4.9

**Comment by pocinhas** [comment] 2023-02-04 19:18
what about in "immersive-portals-2.3.1-mc1.19.2-fabric.jar"?

**Comment by pocinhas** [comment] 2023-02-04 20:01
tested, and no, still broken on that version

**Comment by qouteall** [comment] 2023-02-05 01:08
@spaghettube Do you mean that it still crashes in 2.4.9? Post the new crash report. 

The fix is not backported to 1.19.2. The 2.3.1 was an old version that was not released on CurseForge. Only 1.19.3 is maintained for now because development effort is limited.

**Comment by qouteall** [comment] 2023-02-05 06:25
The packet handling should normally occur in client thread, so accessing the random won't cause an issue. However the packet is acually handled from networking thread. This may be caused by other optimization mods.

I tested ImmPtl 2.4.9 with RLSL and it doesn't crash. Close issue for now. However, there may be some optimization mods that interfere with this issue. If you find a three-mod incompatibility issue, open another issue.

**Closed as completed by qouteall** 2023-02-05 06:25 UTC
Labels: Mod Compatibility, Awaiting Reply

**Comment by pocinhas** [comment] 2023-02-05 20:45
> @spaghettube Do you mean that it still crashes in 2.4.9? Post the new crash report.
> 
> The fix is not backported to 1.19.2. The 2.3.1 was an old version that was not released on CurseForge. Only 1.19.3 is maintained for now because development effort is limited.

~~I have not tested 2.4.9 as I'm stuck on 1.19.2 for now. I meant it was still the same on the latest 1.19.2, 2.3.1. If it's fixed on 1.19.3 I'm glad, and I'll just have to hope that you'll eventually decide to port the fix to 1.19.2. Thanks regardless :)~~

Edit: Misunderstood the whole situation. So a third mod should be interfering with ImmPtl and RSLS? Well if I do figure out which one is doing that I'll open a new issue. Any lead to what I should be looking for?
