### ISSUE TITLE
incompatibilities

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#57] opened 2020-01-15 03:25 UTC
Simple void world intereaction

When using the portal block to get there the portal floor and ceiling are not active until I restart the game.

When I fly down from here to the overworld fences and a few other things stop rendering until I reload the game.

I don't like that void world portal sky is black when it is not a black dimension

 

The Hallow interaction

same thing with the fences, when using the hallow charm to get to hallow via the gate, the portal sky is not active until restart.

when I use the overworld portal floor to go to the hallow the hallow charm does not work to get the player back to the hallow gate.

 

If you die when you fall through a floor that should have a portal but does not have a portal because you took the normal way in, and become a demon with the mod requiem the game looses track of NBT values in the serializer for the mods bulky shulkies and tech reborn, removing these mods does not allow the player to reload the world.     The only fix I found was to make a whole new instance, because when this happens the instance becomes so corrupt that fabric stops loading and only vanilla minecraft loads.

**Comment by AltimusX** [comment] 2020-01-19 06:19
This is an account of what happens with an entity that goes from the overworld, to simple void, the end, nether the hallow, it does not matter what ceiling/floor portal is used, fences always turn invisible. when said entity returns back to the overworld.
And it does happen at any speed. The screenshot is of my standing on an invisible fence, and of the log trying desperately trying to put the player on the ground.
http://prntscr.com/qppqnm
The log snippet here shows what happened to cause the fences to turn invisible. I have a theory and it might have something to do with entity logging.  
When you try to push a minecart through a portal, what happens? How about a boat? This interaction might be the root cause of what is making these portals react to things like a possessed entity in requiem or missing render models for fences and other logged entities. Also for forgetting what state an entity might be in at the moment of entry and the moment of exiting the portal. Maybe this is something minecraft does in the background when going through portals in the first place? 

[00:51:42] [main/INFO]: [Portal] Client Changed Dimension from minecraft:overworld to simplevoidworld:void time: 1022
[00:51:42] [main/INFO]: [Portal] Portal Number Near Player Now0
[00:51:42] [Server thread/INFO]: [Portal] AltimusX teleported from minecraft:overworld class_2338{x=-526, y=254, z=-722} to simplevoidworld:void class_2338{x=-526, y=-2, z=-722}
[00:52:32] [main/ERROR]: [Portal] The Player is Moving Too Fast!
[00:52:35] [main/INFO]: [Portal] Client Changed Dimension from simplevoidworld:void to minecraft:overworld time: 2083
[00:52:35] [main/INFO]: [Portal] Portal Number Near Player Now0
[00:52:35] [Server thread/INFO]: [Portal] AltimusX teleported from simplevoidworld:void class_2338{x=-526, y=-5, z=-722} to minecraft:overworld class_2338{x=-526, y=251, z=-722}
[00:52:35] [main/ERROR]: [Portal] The Player is Moving Too Fast!
[00:52:36] [main/ERROR]: [Portal] The Player is Moving Too Fast!
[00:52:37] [main/ERROR]: [Portal] The Player is Moving Too Fast!
[00:52:42] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -524.000573154433 67.0 -719.6922913376726
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.9483578862918 67.0 -719.609360242799
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.9483578862918 67.0 -719.609360242799
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.938841304021 67.0 -719.5922256380607
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.938841304021 67.0 -719.5922256380607
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.9311674473319 67.0 -719.5741903409812
[00:52:43] [Server thread/INFO]: [Portal] request teleport AltimusX in minecraft:overworld to -523.9311674473319 67.0 -719.5741903409812

**Closed as completed** 2020-03-02 06:43 UTC
