### ISSUE TITLE
crash client in new version  immersive-portals-0.23-mc1.16.1-fabric

### ISSUE THREAD

**Issue by Grecoton** [qouteall/ImmersivePortalsMod#360] opened 2020-07-28 15:13 UTC
The crash happens instantly when you start the game
Fabric API Version: fabric-api-0.16.0+build.384-1.16.1
Loader: 0.9.0+build.204
[crash-2020-07-28_10.11.17-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/4989248/crash-2020-07-28_10.11.17-client.txt)
[latest.log](https://github.com/qouteall/ImmersivePortalsMod/files/4989251/latest.log)

**Comment by qouteall** [comment] 2020-07-29 01:48
probably get fixed on 0.24

**Comment by Imacat-PlaysGames** [comment] 2020-07-29 20:03
it happened to me to

**Comment by qouteall** [comment] 2020-07-30 00:19
@Imacat-PlaysGames shiw the crash report

**Comment by ttamttamS** [comment] 2020-07-31 01:25
Same issue here, running 0.24
[crash-2020-07-27_15.15.30-client.txt](https://github.com/qouteall/ImmersivePortalsMod/files/5004532/crash-2020-07-27_15.15.30-client.txt)

**Comment by qouteall** [comment] 2020-07-31 01:31
@ttamttamS The crash report shows that you are using 0.21

**Comment by ttamttamS** [comment] 2020-07-31 01:31
I take it back, I thought I updated to 0.24 but I was actually using 0.23

**Comment by ttamttamS** [comment] 2020-07-31 01:34
That's weird that it lists it as 0.21, I have some weird syncing madness going on in my .minecraft folder, it might have been related to that. Regardless the issue is gone for me after updating. Apologies for wasting your time

**Comment by Xicad** [comment] 2020-08-17 04:16
I still get this error in 0.27 [1.16.1]

Edit: nvm i fixed it, removed sodium

**Closed as completed** 2020-09-22 14:20 UTC
