### ISSUE TITLE
When I go through portals my items in my hotbar and creative menu go invisible??? 

### ISSUE THREAD

**Issue by MrMean4191** [qouteall/ImmersivePortalsMod#840] opened 2021-09-01 21:04 UTC
I use 1.17.1 version and the newest stuff.

**Comment by qouteall** [comment] 2021-09-02 07:03
Are you using other mods such as optifine?

**Comment by lunathir** [comment] 2021-09-09 04:57
This occurs to me as well, even with literally only three mods: Fabric API, Mod Menu, and Immersive Portals. It looks to me like it maybe everything's clipping very poorly once you look into a portal? F3+T fixes the inventory issue, but it doesn't stop the player model's clipping issues. 

Seeing player/held item models being cut off and what is cut off changing (it's as if a plane is intersecting the player and items, forcing faces and parts of faces between it and the camera to not render) change while rotating the camera in third person leads me to believe that it is a clipping issue. I'm not sure how much I can help past this, but it's the same whether 3 mods or 87, which makes me think it's between Minecraft, Immersive Portals, and Fabric.

**Comment by qouteall** [comment] 2021-09-09 12:12
@lunathir I made some change of clipping code that may fix it https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.27-1.17

**Comment by lunathir** [comment] 2021-09-10 00:08
First person and the inventory do still seem to be a bit buggy, but it certainly helps a lot. The hand/inventory still _do_ disappear, but a workaround is as easy as looking away from the portal and switching to third person and back, whereas release 0.26 doesn't change anything if you do the same thing, and the only thing to fix it in that version is if you walk out from a looping portal in a very specific way. Third person looks to be fixed otherwise, though. It also seems to happen with mirrors.

The following folder has a video showing the issues in the current prerelease in a little more detail though, since GH doesn't particularly enjoy files over 10mb.
https://drive.google.com/file/d/12RLbXT32nq-1v-62p0M7CkwuH7zgnfUx/view?usp=sharing

**Comment by qouteall** [comment] 2021-09-10 09:15
@lunathir The video is not being shared.

**Comment by lunathir** [comment] 2021-09-10 12:41
Oh sorry, I probably set up the folder wrong. Maybe try again, and if it doesn't work maybe use this link?
https://drive.google.com/file/d/12RLbXT32nq-1v-62p0M7CkwuH7zgnfUx/view?usp=drivesdk

**Comment by qouteall** [comment] 2021-09-11 08:40
@lunathir  I can see the video now. I cannot reproduce the issue, can you upload the world? And I made some rendering changes in this version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.28-1.17  which may affect the issue

**Comment by lunathir** [comment] 2021-09-11 12:43
OKAY OKAY OKAY
So I did a bit of testing on my desktop, which has an nVidia card (GT 720), while my laptop has Intel HD 4000... and it really looks like it's an Intel issue for some reason? That might explain why you couldn't replicate the issue. The problem's still there on my laptop but it was never there on the desktop.
Desktop - 8gb RAM, nVidia GT 720, Pentium G2030
Laptop - 8gb RAM, Intel HD Graphics 4000, Core i5 3340m

**Comment by qouteall** [comment] 2021-12-13 10:47
Merged to https://github.com/qouteall/ImmersivePortalsMod/issues/916

**Closed as completed by qouteall** 2021-12-13 10:47 UTC
Labels: Not ImmPtl's Fault
