### ISSUE TITLE
Unbreakable blocks in dimension below player's dimension when that dimension's height is high

### ISSUE THREAD

**Issue by SuperCatMaster** [qouteall/ImmersivePortalsMod#1465] opened 2023-10-23 15:20 UTC
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

When I try to break a block in the dimension below overworld, it doesn't breaks. Idk, maybe it because my custom datapack dimension (inside my custom mtweaks mod), but with nether it works fine on 1.20,2
[Here's a video with a bug.](https://www.youtube.com/watch?v=5Gl1APrIhHo)
[Here's log.](https://pastebin.com/5gGrCnDt)
[Here's mods and configs.](https://drive.google.com/file/d/1WaRpS2KsTQ_6sgvjbNYuaHVWDUcVuUnS/view?usp=sharing)

**Comment by qouteall** [comment] 2023-10-24 12:33
~~Collective is reported to have compat issues with ImmPtl. Does the issue occur with only ImmPtl, mtweaks and Fabric API?~~

I can reproduce the issue

**Comment by qouteall** [comment] 2023-10-24 12:44
I tested dimension stack with this dimension datapack https://modrinth.com/datapack/deeper_dark/version/2.2.1  and it works normally. This is probably caused by speciality of mtweaks.

**Comment by SuperCatMaster** [comment] 2023-10-25 16:26
Well, in mtweaks there are no mixins with blocks nor dimensions. mtweaks is used to load datapacks with dimensions (I test some mtweaks features in the IDE), so the problem is clearly not mtweaks.
I also tested the datapack only stiuation and the problems occurred again.
I used the misode tool to create the datapacks, so I don't think there will be any problems.
Maybe because of the height of the world? This is about 800 blocks.

**Comment by qouteall** [comment] 2023-10-27 13:04
Can you upload the datapack so that I can test it?

**Comment by SuperCatMaster** [comment] 2023-10-27 15:55
[tarta.zip](https://github.com/iPortalTeam/ImmersivePortalsMod/files/13191001/tarta.zip)
There it is. Have to work with uploaded configs.

**Comment by qouteall** [comment] 2023-10-28 00:13
I can reproduce the issue with only the datapack

**Comment by qouteall** [comment] 2023-10-28 00:21
I found that it's caused by a mistake in code

https://github.com/iPortalTeam/ImmersivePortalsMod/commit/16e5784562bceb5a0f1b111f15c02ed2d15b69bd

Now fixed. You are correct that the bug is triggered because of the height.

**Comment by qouteall** [comment] 2023-10-28 00:40
fixed in 3.3.5 https://modrinth.com/mod/immersiveportals/version/v3.3.5-mc1.20.1

**Closed as completed by qouteall** 2023-10-28 00:40 UTC
Labels: Fixed in the next version
