### ISSUE TITLE
Slime blocks extended by pistons sometimes fail to launch boats when immersive portals is installed

### ISSUE THREAD

**Issue by tiggerbiggo** [qouteall/ImmersivePortalsMod#669] opened 2021-04-11 21:18 UTC
Latest version 0.88
Fabric API 0.32.5
No other mods

Steps to reproduce:

Build a sticky piston with a slime block under 1 block of water as shown, and attach a clock to make it extend the piston repeatedly. Get in a boat and move onto the slime block. Sometimes you will be launched as expected, but other times the boat will not launch high into the air and will only move a small distance above the water.

![image](https://user-images.githubusercontent.com/19495086/114321657-cd8a2a00-9b13-11eb-8df1-1aef11450383.png)

![boatbug](https://user-images.githubusercontent.com/19495086/114321665-d5e26500-9b13-11eb-8c46-585b9df0597c.gif)

when the bug happens it acts as if the boat has hit an invisible roof and does not reach nearly the full height it is supposed to. See video for explanation.

Loading the same world with either a vanilla 1.16.5 client or with only fabric + api installed results in the boat launching 100% of the time.

**Comment by qouteall** [comment] 2021-04-12 07:20
Seems weird

**Comment by qouteall** [comment] 2021-04-21 11:56
I can randomly reproduce this issue now

**Comment by qouteall** [comment] 2021-04-21 13:24
This issue seems to be very complex, related to position syncing, entity tracking and collision

**Comment by qouteall** [comment] 2021-04-21 13:52
Minecraft sets server-side boat velocity to 0 because the boat movement is not updated on server. But it still sends velocity sync packets to client to reset client-side boat velocity. But normally server also sends the vehicle move packets which cancels that effect. The reason that this issue does not manifest in vanilla may be more complex.
I made it to not wrongly sync the velocity and the issue is probably fixed (I cannot reproduce it now)

**Comment by qouteall** [comment] 2021-04-21 13:55
Probably fixed in this preview version https://github.com/qouteall/ImmersivePortalsMod/releases/tag/v0.91-1.16

**Closed as completed** 2022-11-19 02:11 UTC
