### ISSUE TITLE
Both client in singleplayer and server hosting game hang when saving world with Immersive Portals installed

### ISSUE THREAD

**Issue by awdwyn** [qouteall/ImmersivePortalsMod#1455] opened 2023-10-02 12:39 UTC
### Is it a mod compatibility issue?

No

### Minecraft version

1.20.1

### Describe the issue

Troubleshooting a hang when shutting down my server after saving chunks / worlds. I narrowed it down to this mod by removing / readding mods in singleplayer as the issue is present on both my server and in a singleplayer client world.

Removed all mods then redownloaded / reinstalled fabric 0.89.3 and immersive portals 3.3.2. The issue persisted. Added in sodium 0.5.3 and indium 1.0.27 with no benefit. Also tried removing the immersive portals config file to no avail.

Process used was to load the game and create a new singleplayer world with default settings, then after it loaded, quick to the main menu. Used task manager to kill the jvm after a few minutes of looking at the Saving World screen and no progress in the latest.log file.

Log attached (via pastebin): [https://pastebin.com/K4kW2fcB](https://pastebin.com/K4kW2fcB)

**Comment by qouteall** [comment] 2023-10-02 14:29
~~I cannot reproduce this issue on my PC.~~

~~MC is probably stuck in chunk generation when saving world (Once chunk generation starts it cannot halt when exiting world). When the free memory amount is low, the chunk generation process may trigger long GC pauses frequently so it hangs. Have you allocated more than 2000 MB of memory to Minecraft~~

~~Does it hang when render distance (or server loading distance) is set to 2?~~

**Comment by qouteall** [comment] 2023-10-02 14:35
I can reproduce the issue when setting render distance to 32 and use amplified world

**Comment by qouteall** [comment] 2023-10-02 15:10
Should be fixed in 3.3.3

**Closed as completed by qouteall** 2023-10-02 15:10 UTC
Labels: IMPORTANT
