### ISSUE TITLE
[MC: 1.17.1] [IP: 0.20.0] Not quite compatible with base Iris

### ISSUE THREAD

**Issue by Merith-TK** [qouteall/ImmersivePortalsMod#815] opened 2021-08-05 18:29 UTC
Game logs, 
https://paste.ee/p/e1C8O

Iris + Complimentary shaders
Shaders constantly "reload", causing a memory leak

https://cdn.merith.tk/assets/minecraft/ip-iris.mp4 
Sorry you will have to download the MP4, I dont know how to get the file to actually open in your browser on my server.

Using Indium results in it *not dying* like this, but the nether flickers, to hell and back, allowing someone to see the "lightmap" that is in use for some reason.

DrakoSoldier should be posting something to add onto this as she was the one testing with indium

**Comment by AlsoSylv** [comment] 2021-08-05 18:42
Iris and immersive portals are not compatible yet

**Comment by Merith-TK** [comment] 2021-08-05 18:44
Well in our testing they are *sorta* compatible, like it doesnt immediately crash. 

And Indium helps out *alot*, but it is still problematic enough to say its not compatible, 

Just figured we would atleast report this to you guys so you know whats up

**Comment by RemagOfficial** [comment] 2021-08-05 18:50
they arent incompatible as they work together somewhat but support for iris is being worked on iirc

**Comment by Merith-TK** [comment] 2021-08-05 18:54
One can use Iris for the performance benifits right now, but Iris+Shaders breaks things,

**Comment by RemagOfficial** [comment] 2021-08-05 19:09
iris doesnt do performance tho...

**Comment by drakosoldier298** [comment] 2021-08-05 19:17
While base iris is incompatible iris+indium fixes the incompatibility issue almost entirely apart from a bit of flashing
video attatched also YES IRIS DOES PERFORMANCE it bundles sodium WHICH IS BLOODY PERFORMANCE
video https://mega.nz/file/urpk2bLY#75EKuwxvwTsOTxcAXiaP4mJuJ5d2Fr_OqtoBXTPTq1o

**Comment by Merith-TK** [comment] 2021-08-05 19:19
Yes it does, it bundles a custom verison of sodium *which is a performance boosting mod*, built for use specifically with Iris.

**Comment by froyo4u** [comment] 2021-08-05 19:19
Remag is not incorrect. Iris itself does not do performance.

**Comment by Merith-TK** [comment] 2021-08-05 19:21
Meow, that is being nitpicky as while yes, you are correct, Iris loads Sodium, so therefore, by proxy, it is a performance mod

**Comment by Merith-TK** [comment] 2021-08-05 19:26
----
# TO MAKE THIS CLEAR
Iris and Immersive Portals Causes a Memory leak, which I have been informed by Iris Contributors/Devs, is currently in progress of being fixed inside a PR, 

### HOWEVER, In its current State, Indium makes IP/IRIS not give the game a heart attack outside of the aforementioned memory leak issues and flickering

**Comment by qouteall** [comment] 2021-08-06 02:05
IP is not yet compatible with the official iris

**Comment by qouteall** [comment] 2021-08-06 02:38
Does the memory leak occur with this Iris? https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1

**Comment by Merith-TK** [comment] 2021-08-06 15:46
> IP is not yet compatible with the official iris

We have already established this.
We have also established that the indium mod makes it have *less* of a heart attack on the player, (memory leak still exists) 

I will either test it myself or have someone test it when possible

**Comment by Merith-TK** [comment] 2021-08-06 16:57
Testing with Indium, works flawlessly, 

Without Indium, works the same, 

Let me test with shaders

**Comment by Merith-TK** [comment] 2021-08-06 16:59
![image](https://user-images.githubusercontent.com/10422110/128545920-d5f048b8-e9f2-4767-bc47-f3bc1f82d941.png)
Works with Complimentary Shaders which are compatible with Iris

**Comment by SirPytan** [comment] 2021-08-28 18:46
I use Iris(+Sodium), Lithium, Starlight, Complementary Shaders, and Indium, and some more performance increasing mods and some other mods as well. The game does not crash, but I get 1fps (probably even lower) when starting looking at the portal.

**Comment by MrBones1102** [comment] 2021-08-28 19:05
> I use Iris(+Sodium), Lithium, Starlight, Complementary Shaders, and Indium, and some more performance increasing mods and some other mods as well. The game does not crash, but I get 1fps (probably even lower) when starting looking at the portal.

Your problem here is Starlight. Using the iris and sodium versions provided by Qouteall will fix this.

**Comment by SirPytan** [comment] 2021-08-28 19:08
> I use Iris(+Sodium), Lithium, Starlight, Complementary Shaders, and Indium, and some more performance increasing mods and some other mods as well. The game does not crash, but I get 1fps (probably even lower) when starting looking at the portal.

Ok, thanks, for the answer. Might be worth it merge it with the latest changes from HyperCubeMC.

**Comment by SirPytan** [comment] 2021-08-28 19:20
After trying that(https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1) version I get this error:
And can't start the game.
[21:18:09] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: sodium requires {iris @ [>=1.1.0-pre]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more

**Comment by MrBones1102** [comment] 2021-08-28 20:04
I'm sorry, when I replied to your comment, I misread "starlight" as "starline." I do not actually know your problem, although I do suspect that using Qouteall's Iris AND sodium (they are separate) versions will improve your performance anyway if you are not already doing so.

As for your current crash, you might not have included the sodium file.  Both files are found here https://github.com/qouteall/Iris/releases/tag/ipc1.1.1_1

I get reasonable performance using the linked files, along with Indium, Lithium, and Complementary Shaders

**Comment by SirPytan** [comment] 2021-08-28 20:07
@MrBones1102 Do I need both files?

**Comment by SirPytan** [comment] 2021-08-28 20:08
Because I downloaded the sodium named file from him and thought I just need that because it sayed it has both.

**Comment by SirPytan** [comment] 2021-08-28 20:09
Else, I will just disable immersive portals for now and use it when Iris got an official update that works.

**Comment by MrBones1102** [comment] 2021-08-28 20:10
The only way I could get it to work was with both files. I downloaded and installed both https://github.com/qouteall/Iris/releases/download/ipc1.1.1_1/iris-mc1.17-1.1.1+rev.7839591-dirty.jar and https://github.com/qouteall/Iris/releases/download/ipc1.1.1_1/sodium-fabric-mc1.17.1-0.3.0+IRIS2-rev.b05914e.jar files. This worked for me.

**Comment by SirPytan** [comment] 2021-08-28 20:11
@MrBones1102 Ok, I will test it, thanks.

**Comment by DragonEggBedrockBreaking** [comment] 2021-08-29 10:26
The pr was merged into iris a few hrs ago

**Closed as completed** 2021-09-18 14:03 UTC
