### ISSUE TITLE
Ticking entity crash using Fabric API and Immersive Portals

### ISSUE THREAD

**Issue by TheSpiderDungeon** [qouteall/ImmersivePortalsMod#215] opened 2020-05-03 12:06 UTC
https://pastebin.com/mQ3q4MrK

What have I done wrong? I started a world in creative using default settings, and it's a consistent CTD. Removing Immersive Portals fixes the issue,

**Comment by LoganDark** [comment] 2020-05-03 12:07
Are you sure the version of IP you're using matches your Minecraft version? Sounds like some intermediate mappings don't exist, which makes me think you have mismatched versions.

**Comment by TheSpiderDungeon** [comment] 2020-05-03 12:09
I'm using 0.27 in this particular instance to see if switching to an older version fixes it, but 0.28 does the same thing. The MC version is 1.15.1 with the 1.15 version of IP.

**Comment by TheSpiderDungeon** [comment] 2020-05-03 12:12
https://pastebin.com/b9W90w9K

Here's the report on a new world using the latest IP and Fabric API

**Comment by LoganDark** [comment] 2020-05-03 12:16
The 1.15 version of IP is for 1.15.2, not 1.15.1.

**Comment by TheSpiderDungeon** [comment] 2020-05-03 12:17
Man, that's the first time I've ever seen a minor version matter. I'll DL 1.15.2 and see if that makes a difference.

**Comment by LoganDark** [comment] 2020-05-03 12:18
Yeah, IP is developed on 1.15.2 rather than 1.15 so classes added in minor versions matter. Not much I can do about it, @qouteall set it up.

**Comment by TheSpiderDungeon** [comment] 2020-05-03 12:21
Yup, that was the issue. I'll have to keep an eye on that from now on for future weird crashes. Thank you!

**Comment by LoganDark** [comment] 2020-05-03 12:23
I feel like this issue should be fixed. Or @qouteall can close it if they think it's WAI (working as intended)

**Comment by qouteall** [comment] 2020-05-03 12:25
work as intended

**Closed as completed by qouteall** 2020-05-03 12:25 UTC
